advent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cards/', include('cards.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

cards/urls.py
from django.urls import path

from . import views

app_name = 'cards'

urlpatterns = [
    # ex: /cards/
    path('', views.index, name='index'),
    # ex: /cards/5/
    path('<int:calendar_id>/', views.cards, name="cards"),
    path('calendar/', views.edit_calendar, name='create_calendar'),
    path('calendar/<int:calendar_id>/', views.edit_calendar, name='edit_calendar'),
    path('calendar/<int:calendar_id>/delete/', views.delete_calendar, name='delete_calendar'),
    path('<int:pk>/create-card/', views.create_card, name='create_card'),
    path('htmx/create-card-form/', views.create_card_form, name='create-card-form'),
    path('htmx/card/<pk>/', views.detail_card, name='detail-card'),
    path('htmx/card/<pk>/delete/', views.delete_card, name='delete-card'),
    path('htmx/card/<pk>/update/', views.update_card, name='update-card'),
]

core/urls.py
from django.urls import path 

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

cards/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField

from accounts.models import User 

class Calendar(models.Model):
    name = models.CharField(max_length = 255)
    created_by = models.ForeignKey(User, related_name='calendars', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    available_from = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created_at', ) #- for descending

class Card(models.Model):
    calendar = models.ForeignKey(Calendar, related_name='cards', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='cards', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    ordering = models.IntegerField()
    text = RichTextField()
    available_from = models.DateTimeField()
    style = models.CharField(max_length=255, default='bg-gray-100')

    def is_available(self):
        return self.available_from < timezone.now()
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ('ordering',)

cards/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from ckeditor.widgets import CKEditorWidget

from .models import Calendar, Card 

class CalendarForm(forms.ModelForm):
    class Meta: 
        model = Calendar
        fields = ('name','available_from')

class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = ('calendar', 'name', 'text', 'available_from')
        widgets = {
            'available_from' : forms.TextInput(attrs={'type':'datetime-local'}),
            'text' : CKEditorWidget()
        }

CardFormSet = inlineformset_factory(
    Calendar, 
    Card,
    form = CardForm,
    min_num = 1,
    can_delete=False,
    extra = 0 #see what it does
)

cards/views.py
import random

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_list_or_404
from django.http import HttpResponse, Http404

from .forms import CalendarForm, CardForm, CardFormSet
from .models import Calendar, Card

def index(request):
    return HttpResponse("Hello, world. You're at the calendars index.")

# @login_required
def cards(request, calendar_id):
    cards = get_list_or_404(Card, calendar__id=calendar_id)
    
    # hardcoded randomization
    random.shuffle(cards)

    return render(request, 'cards/cards.html', {
        'cards': cards,
    })

    # print(request.GET.get('id'))
    # cards = Card.objects.filter(available_from__lte = datetime.datetime.now())

@login_required
def create_card(request, pk):
    """
    pk - ID of the calendar
    """
    calendar = Calendar.objects.get(pk=pk)
    cards = Card.objects.filter(calendar=calendar)
    form = CardForm(request.POST or None)
   
    print("CreateCard")

    if request.method == 'POST':
        if form.is_valid():
            card = form.save(commit=False)
            card.calendar_id = pk
            card.created_by = request.user
            card.ordering = 1
            card.save()
            # formset.instance = calendar
            # new_card = formset.save(commit=False)
            # for nc in new_card:
            #     nc.created_by = request.user
            #     # TODO: clean this up
            #     nc.ordering = 1 
            # formset.save()

            # return redirect('/cards/htmx/card/{}/'.format(calendar.id))
            return redirect('/cards/htmx/card/{}/'.format(card.id))
        else:
            return render(request, 'cards/create_card_component.html', {
                "form": form
            })
    #     form = CardForm(request.POST)

    #     if form.is_valid():
    #         card = form.save(commit=False)
    #         card.created_by = request.user
    #         card.save()

    #         return redirect('/dashboard/')
    # else:
    #     form = CardForm()
    #     form.fields['calendar'].queryset = Calendar.objects.filter(created_by=request.user)

    return render(request, 'cards/create_card.html', {
        "form" : form,
        "calendar" : calendar,
        "cards": cards
    })

@login_required
def create_card_form(request):
    return render(request, 'cards/create_card_component.html', {
        "form": CardForm()
    })

@login_required
def detail_card(request, pk):
    card = Card.objects.get(pk=pk)
    return render(request, 'cards/card_detail_component.html', {
        "card": card
    })

@login_required
def delete_card(request, pk):
    card = Card.objects.get(pk=pk)
    card.delete()
    return HttpResponse('')

@login_required
def update_card(request, pk):
    card = Card.objects.get(pk=pk)
    form = CardForm(request.POST or None, instance=card)

    print("UpdateCard")

    if request.method == 'POST':
        card_text = request.POST.get('text', '')
        print("CARD TEXT:")
        print(card_text)
        if form.is_valid():
            card = form.save(commit=False)

            # TODO: hardcoded claendar id and ordering!!!
            card.calendar_id = 1
            card.created_by = request.user
            card.ordering = 1
            card.save()
            return redirect('/cards/htmx/card/{}/'.format(card.id))

    return render(request, 'cards/create_card_component.html', {
        "form": form,
        "card": card
    })

# @login_required
# def create_calendar(request):
    

@login_required
def edit_calendar(request, calendar_id=None):
    # the '0' here is a workaround, I don't know how to allow just cards:edit_calendar
    if calendar_id is None or calendar_id == 0:
        print("create calendar")
        if request.method == 'POST':
            form = CalendarForm(request.POST)

            if form.is_valid():
                calendar = form.save(commit=False)
                calendar.created_by = request.user
                calendar.save()

                print("saving new clendar")

                return redirect('/dashboard/')
        else:
            form = CalendarForm()

        return render(request, 'cards/calendar.html', {
            'form': form,
        })
    else:
        print("edit calendar")
        calendar = Calendar.objects.get(id = calendar_id)
        form = CalendarForm(instance=calendar)
        if request.method == 'POST':
            form = CalendarForm(request.POST, instance=calendar)
            if form.is_valid():
                calendar = form.save(commit=False)
                calendar.save()

                print("saving updated clendar")

                return redirect('/dashboard/')
        else:
            print(request.method)
            
        return render(request, 'cards/calendar.html', {
            'form': form,
            'calendar': calendar,
            # 'calendar_id': 123
        })
    
@login_required
def delete_calendar(request, calendar_id=None):
    print("delete calendar")
    calendar = Calendar.objects.get(id = calendar_id)
    calendar.delete()

    return redirect('/dashboard/')

cards/templates/cards/calendar.html
{% extends 'core/base.html' %}

{% block title %}Edit calendar{% endblock %}

{% block content %}
    <h1 class="text-xl">Edit calendar</h1>

    {% if calendar %}
    <form action="{% url 'cards:edit_calendar' calendar.id %}" method="post">
    {% else %}
    <form action="{% url 'cards:edit_calendar' 0%}" method="post">
    {% endif %}

        {% csrf_token %}

        {{ form.as_p }}

        <button class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Save</button>

    </form>
{% endblock %}

cards/templates/cards/card_detail_component.html
<div hx-target="this" hx-swap="outerHTML">
    <h3>{{ card.name }}</h3>
    <p>Dostępne od: {{card.available_from}}</p>

    <button hx-get="{% url 'cards:update-card' card.id %}">Update</button>
    <button hx-post="{% url 'cards:delete-card' card.id %}">Delete</button>
</div>

cards/templates/cards/cards.html
{% extends 'core/base.html' %}

{% block title %}Cards{% endblock %}

{% block content %}
    <h1 class="mb-6 text-xl">Cards</h1>

    <div class="grid grid-cols-3 gap-4">
        {% for card in cards %}

            {% if card.is_available %}
                <button data-modal-target="#modal_{{card.id}}">
            {% else %}
                <button>
            {% endif %}
                    <div class="{{card.style}} p-6 rounded-xl">
                        <h2 class="text-xl">{{ card.name }}</h2>
                        <!-- <p class="text-xs" data-available-at="{{card.available_from|date:'U'}}">Dostępny od: {{ card.available_from }}</p> -->
                        <p class="text-xs" data-available-at="{{card.available_from|date:'U'}}"></p>
                    </div>
                </button>
            {% if card.is_available %}
                <div class="modal text-center" id="modal_{{card.id}}">
                    <div class="modal-header">
                        <div class="title m-auto">
                            {{card.name}}
                        </div>
                        <button data-close-button class="close-button">&times;</button>
                    </div>
                    <div class="modal-body" id={{card.id}}>
                        {{ card.text|safe}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}

        <div id="overlay"></div>
    </div>

    

    <!-- <button id="openModalBtn">Open Modal</button>
    <div class="modal-wrapper" id="modal">
        <div class="modal">
            <div class="modal-header">
                <h3>Modal Header</h3>
            </div>
            <div class="modal-body">
                <h4>Modal Body</h4>
                <p>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                    Quaerat, enim. Cupiditate, ab? Atque ut soluta fugit repellat
                    perferendis mollitia. Omnis.
                </p>
            </div>
            <div class="modal-footer">
                <button id="closeModalBtn">Close</button>
            </div>
        </div>
    </div> -->

    {% load static %}
    <link rel="stylesheet" href="{% static 'cards/style.css' %}">
    <script src="{% static 'cards/code.js' %}"></script>

{% endblock %}

cards/templates/cards/create_card.html
{% extends 'core/base.html' %}

{% block title %}Create card{% endblock %}

{% block content %}
    <h1 class="text-xl">Create advent card</h1>

    <button hx-get="{% url 'cards:create-card-form' %}" hx-swap="beforeend" hx-target="#cardforms" class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">
        Add Card
    </button>

    <div id ="cardforms">
        {% for card in cards %}
        {% include 'cards/card_detail_component.html' %}
        {% endfor %}
    </div>

{% endblock %}

cards/templates/cards/create_card_component.html
<div hx-target="this" hx-swap="outerHTML">
    <form method="POST"> 

        <script>
            document.body.addEventListener('htmx:configRequest', (event) => {
                var element = new CKEDITOR.dom.element( document.getElementById( '{{ form.text.id_for_label }}' ) );
                event.detail.parameters['{{ form.text.html_name }}'] = element.getEditor().getData();        
            })
        </script>

        {% csrf_token %}
        
        {{ form.media }}
        {{ form }}



        {% if card %}
            <button hx-post="{% url 'cards:update-card' card.id %}" class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Save</button>
        {% else %}
            <button hx-post="." class="mt-4 py-4 px-6 bg-cyan-500 text-white rounded-xl">Create</button>
        {% endif %}

    </form>
</div>