accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path 

from . import views 
from . forms import LoginForm

app_name = 'accounts'

urlpatterns  = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html', form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

advent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cards/', include('cards.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

cards/urls.py
from django.urls import path

from . import views

app_name = 'cards'

urlpatterns = [
    # ex: /cards/
    path('', views.index, name='index'),
    # ex: /cards/5/
    path('<int:calendar_id>/', views.cards, name="cards"),
    path('calendar/', views.edit_calendar, name='create_calendar'),
    path('calendar/<int:calendar_id>/', views.edit_calendar, name='edit_calendar'),
    path('calendar/<int:calendar_id>/delete/', views.delete_calendar, name='delete_calendar'),
    path('<int:pk>/create-card/', views.create_card, name='create_card'),
    path('htmx/create-card-form/', views.create_card_form, name='create-card-form'),
    path('htmx/card/<pk>/', views.detail_card, name='detail-card'),
    path('htmx/card/<pk>/delete/', views.delete_card, name='delete-card'),
    path('htmx/card/<pk>/update/', views.update_card, name='update-card'),
]

core/urls.py
from django.urls import path 

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1 class="text-xl">About advent calendar!</h1>
{% endblock %}

core/templates/core/base.html
{% load static tailwind_tags %}

<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- <script src="https://cdn.tailwindcss.com"></script> -->
        {% tailwind_css %}
        
        <title>
            {% block title %}{% endblock %} | advent calendar
        </title>

    </head>
    <body>
        <div class="flex flex-col h-screen justify-between">
            <nav class="p-6 flex items-center justify-between bg-gray-800">
                <a href="/" class="text-xl text-cyan-500">advent calendar</a>
                
                <div class="space-x-4">
                    <a href="{% url 'core:about' %}" class="text-white">about</a>

                    {% if not request.user.is_authenticated %}
                        <a href="{% url 'accounts:signup' %}" class="py-4 px-6 bg-cyan-600 text-white rounded-xl">sign up</a>
                        <a href="{% url 'accounts:login' %}" class="py-4 px-6 bg-gray-600 text-white rounded-xl">log in</a>
                    {% else %}
                        <a href="{% url 'dashboard:dashboard' %}" class="py-4 px-6 bg-cyan-600 text-white rounded-xl">kalendarze</a>
                        <a href="{% url 'cards:edit_calendar' 0 %}" class="py-4 px-6 bg-cyan-600 text-white rounded-xl">create calendar</a>
                        <!-- <a href="{% url 'cards:create_card' 0 %}" class="py-4 px-6 bg-cyan-600 text-white rounded-xl">create card</a> -->
                        <form class="inline py-4 px-6 bg-rose-600 text-white rounded-xl" method="post" action="{% url 'accounts:logout' %}">
                            {% csrf_token %}
                            <button type="submit">log out</button>
                        </form>
                    {% endif %}
                    
                </div>
            </nav>
        
            <main class="mb-auto p-6">
                {% block content %}
                {% endblock %}
            </main>
    
            <footer class="p-6 bg-gray-900">
                <p class="text-xs text-gray-400"> Copyright (c) 2023 - advent calendar</p>
            </footer>
        </div>

        <script src="https://unpkg.com/htmx.org@1.9.10"></script>
        <script>
            document.body.addEventListener('htmx:configRequest', (event) => {
              event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
            })
          </script>

    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1 class="text-xl">Welcome to advent calendar!</h1>
{% endblock %}