advent/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cards/', include('cards.urls')),
    path('admin/', admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
]

cards/urls.py
from django.urls import path

from . import views

app_name = 'cards'

urlpatterns = [
    # ex: /cards/
    path('', views.index, name='index'),
    # ex: /cards/5/
    path('<int:calendar_id>/', views.cards, name="cards"),
    path('calendar/', views.edit_calendar, name='create_calendar'),
    path('calendar/<int:calendar_id>/', views.edit_calendar, name='edit_calendar'),
    path('calendar/<int:calendar_id>/delete/', views.delete_calendar, name='delete_calendar'),
    path('<int:pk>/create-card/', views.create_card, name='create_card'),
    path('htmx/create-card-form/', views.create_card_form, name='create-card-form'),
    path('htmx/card/<pk>/', views.detail_card, name='detail-card'),
    path('htmx/card/<pk>/delete/', views.delete_card, name='delete-card'),
    path('htmx/card/<pk>/update/', views.update_card, name='update-card'),
]

core/urls.py
from django.urls import path 

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

dashboard/urls.py
from django.urls import path 

from . import views 

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from cards.models import Calendar

@login_required
def dashboard(request):
    newest_calendars = Calendar.objects.filter(created_by=request.user)[0:5]
    return render(request, 'dashboard/dashboard.html', {
        'newest_calendars': newest_calendars
    })

dashboard/templates/dashboard/dashboard.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1 class="mb-6 text-xl">Dashboard</h1>

    <div class="p=6 bg-gray-100 rounded-xl">
        <h2 class="mb-4 text-xl">Recent calendars</h2>

        {% for calendar in newest_calendars %}
            <div class="mb-2 flex justify-between items-center">
                <p>{{ calendar.name }}</p>
                <div>
                    <!-- <a href="#" class="underline">Edit</a> -->
                    <a href="{% url 'cards:edit_calendar' calendar.id %}">Edit</a>
                    <a href="{% url 'cards:delete_calendar' calendar.id %}">Delete</a>
                </div>
            </div>
        {% endfor %}

    </div>
    

{% endblock %}